### ISSUE TITLE
Reset start time to user profile start time if no time logged for current day

### ISSUE THREAD

**Issue by cadjockey** [roguelj/Timer#17]
currently defaults to yesterday date. If this is the first time log of the day it would be better to set the start time to the same as in the user profile, ie the strat of their day.

**Comment by roguelj** [comment]
Doesn't exist in the user profile, I thought it did. Instead, there's a **TimeOfFirstTask** in appsettings.json that will determine the earliest time. If Timer calculates a start time that is _before_ the **TimeOfFirstTask** on the current day, then it sets the start to that start time.
